import type { ShoppingItem } from "./types";

export const shoppingItems: ShoppingItem[] = [
  {
    id: "personal-shampoo",
    scope: "personal",
    ownerUserId: "juli",
    name: "Shampoo",
    quantity: "1",
    category: "Higiene",
    suggestedStore: "Target",
    status: "pending",
    createdByUserId: "juli",
    createdAt: "2026-01-12T10:00:00.000Z",
  },
  {
    id: "personal-snacks",
    scope: "personal",
    ownerUserId: "juli",
    name: "Snacks para el trabajo",
    quantity: "2 packs",
    category: "Comida",
    suggestedStore: "Trader Joe's",
    status: "bought",
    createdByUserId: "juli",
    boughtByUserId: "juli",
    createdAt: "2026-01-11T10:00:00.000Z",
    boughtAt: "2026-01-12T12:00:00.000Z",
  },
  {
    id: "group-milk",
    scope: "group",
    groupId: "casa-tahoe",
    name: "Leche",
    quantity: "2 galones",
    category: "Lacteos",
    suggestedStore: "Safeway",
    status: "pending",
    createdByUserId: "sofi",
    createdAt: "2026-01-12T09:00:00.000Z",
  },
  {
    id: "group-eggs",
    scope: "group",
    groupId: "casa-tahoe",
    name: "Huevos",
    quantity: "24 unidades",
    category: "Desayuno",
    suggestedStore: "Costco",
    status: "pending",
    createdByUserId: "juli",
    createdAt: "2026-01-12T09:05:00.000Z",
  },
  {
    id: "group-paper",
    scope: "group",
    groupId: "casa-tahoe",
    name: "Papel higiénico",
    quantity: "1 pack grande",
    category: "Casa",
    suggestedStore: "Costco",
    status: "bought",
    createdByUserId: "flor",
    boughtByUserId: "matu",
    createdAt: "2026-01-11T18:00:00.000Z",
    boughtAt: "2026-01-12T16:00:00.000Z",
  },
  {
    id: "group-vegas-water",
    scope: "group",
    groupId: "viaje-las-vegas",
    name: "Agua",
    quantity: "12 botellas",
    category: "Bebidas",
    suggestedStore: "CVS",
    status: "pending",
    createdByUserId: "juli",
    createdAt: "2026-02-18T09:00:00.000Z",
  },
];
