import type { CalendarEvent } from "./types";

export const calendarEvents: CalendarEvent[] = [
  {
    id: "personal-work",
    scope: "personal",
    ownerUserId: "juli",
    privacy: "private",
    title: "Trabajo",
    description: "Shift en el cafe",
    category: "Trabajo",
    date: "2026-01-12",
    startTime: "10:00",
    endTime: "17:00",
    allDay: false,
    recurrence: { frequency: "weekdays", interval: 1, daysOfWeek: [1, 2, 3, 4, 5] },
    priority: "normal",
    status: "pending",
    notes: "Llevar uniforme.",
  },
  {
    id: "personal-gym",
    scope: "personal",
    ownerUserId: "juli",
    privacy: "private",
    title: "Gimnasio",
    category: "Salud",
    date: "2026-01-14",
    startTime: "08:00",
    endTime: "09:00",
    allDay: false,
    recurrence: { frequency: "weekly", interval: 1 },
    priority: "normal",
    status: "pending",
  },
  {
    id: "group-bathroom",
    scope: "group",
    groupId: "casa-tahoe",
    kind: "responsibility",
    title: "Limpiar baño",
    description: "Repaso completo del baño compartido",
    category: "Limpieza",
    date: "2026-01-12",
    startTime: "18:00",
    endTime: "19:00",
    allDay: false,
    recurrence: {
      frequency: "weekly",
      interval: 1,
      rotationUserIds: ["juli", "sofi", "flor", "matu"],
    },
    priority: "important",
    status: "pending",
    responsibleIds: ["juli"],
    participantIds: ["juli", "sofi", "matu", "flor", "vicky"],
  },
  {
    id: "group-trash",
    scope: "group",
    groupId: "casa-tahoe",
    kind: "responsibility",
    title: "Sacar basura",
    category: "Casa",
    date: "2026-01-13",
    allDay: true,
    recurrence: {
      frequency: "weekdays",
      interval: 1,
      daysOfWeek: [2, 5],
      rotationUserIds: ["sofi", "vicky"],
    },
    priority: "normal",
    status: "pending",
    responsibleIds: ["sofi"],
    participantIds: ["sofi", "vicky"],
  },
  {
    id: "group-super",
    scope: "group",
    groupId: "casa-tahoe",
    kind: "responsibility",
    title: "Supermercado con Sofi",
    category: "Compras",
    date: "2026-01-12",
    startTime: "19:00",
    endTime: "20:00",
    allDay: false,
    recurrence: { frequency: "none", interval: 1 },
    priority: "important",
    status: "pending",
    responsibleIds: ["juli", "sofi"],
    participantIds: ["juli", "sofi"],
  },
  {
    id: "group-dinner",
    scope: "group",
    groupId: "casa-tahoe",
    kind: "plan",
    title: "Cena grupal",
    category: "Plan",
    date: "2026-01-12",
    startTime: "21:00",
    endTime: "23:00",
    allDay: false,
    recurrence: { frequency: "none", interval: 1 },
    priority: "normal",
    status: "pending",
    responsibleIds: ["juli", "matu"],
    participantIds: ["juli", "sofi", "matu", "flor", "vicky"],
  },
  {
    id: "group-ski",
    scope: "group",
    groupId: "casa-tahoe",
    kind: "plan",
    title: "Ski en Heavenly",
    category: "Plan",
    date: "2026-01-13",
    allDay: true,
    recurrence: { frequency: "none", interval: 1 },
    priority: "urgent",
    status: "pending",
    responsibleIds: ["flor"],
    participantIds: ["juli", "sofi", "flor", "matu"],
  },
  {
    id: "vegas-flight",
    scope: "group",
    groupId: "viaje-las-vegas",
    kind: "plan",
    title: "Vuelo a Las Vegas",
    category: "Transporte",
    date: "2026-02-18",
    startTime: "09:30",
    endTime: "11:00",
    allDay: false,
    recurrence: { frequency: "none", interval: 1 },
    priority: "urgent",
    status: "pending",
    responsibleIds: ["juli"],
    participantIds: ["juli", "sofi"],
  },
];
